version: '3'
services:
  database:
    build: ./docker/mongodb
    container_name: 'mongodb'
    volumes:
      - ./db:/data/db
    logging:
      driver: 'json-file'
    networks:
      api:
    ports:
      - '5525:27017'
  server:
    build: ./docker/node
    container_name: 'topup-api'
    environment:
      - 'NODE_ENV=product'
      - 'mongouri=mongodb://database:5525'
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      sh -c "yarn && yarn production"
    logging:
      driver: 'json-file'
    networks:
      api:
    ports:
      - '2019:2019'
networks:
  api:
